In [4]:
# This reload library is just used for developing the REPUBLIC hOCR parser 
# and can be removed once this module is stable.
%reload_ext autoreload
%autoreload 2


#This is needed to add the repo dir to the path so jupyter
# can load the republic modules directly from the notebooks
import os
import sys
import re

# from collections import defaultdict
import pandas as pd
from collections import Counter, defaultdict

repo_dir = os.path.split(os.getcwd())[0]

if repo_dir not in sys.path:
    sys.path.append(repo_dir)

Requirement already up-to-date: PyMySQL[rsa] in /Users/rikhoekstra/.local/share/virtualenvs/republic-project-Av06XlOZ/lib/python3.8/site-packages (1.0.2)
Requirement already satisfied, skipping upgrade: cryptography; extra == "rsa" in /Users/rikhoekstra/.local/share/virtualenvs/republic-project-Av06XlOZ/lib/python3.8/site-packages (from PyMySQL[rsa]) (35.0.0)
Requirement already satisfied, skipping upgrade: cffi>=1.12 in /Users/rikhoekstra/.local/share/virtualenvs/republic-project-Av06XlOZ/lib/python3.8/site-packages (from cryptography; extra == "rsa"->PyMySQL[rsa]) (1.14.5)
Requirement already satisfied, skipping upgrade: pycparser in /Users/rikhoekstra/.local/share/virtualenvs/republic-project-Av06XlOZ/lib/python3.8/site-packages (from cffi>=1.12->cryptography; extra == "rsa"->PyMySQL[rsa]) (2.20)

# Linking Heinsius, Schutte and RAA

## Heinsius

We start out with the collection of Heinsius documents and surrounding materials from Nederlab

In [5]:
import pandas as pd

In [6]:
basedir = "/Users/rikhoekstra/develop/heinsius_linked/"

In [7]:
lst = os.listdir(basedir)

In [8]:
len(lst)

17958

In [16]:
import gzip, random
from lxml import etree
from lxml import etree
fn = os.path.join(basedir, random.choice(lst))
f=gzip.open(fn,'rb')
file_content=f.read()
#tree = open()
parser = etree.XMLParser(recover=True)
tree = etree.fromstring(file_content, parser)


# print (file_content)

In [ ]:
for e in tree.getchildren()[0].getchildren():
    print(e.attrib)
    children = e.getchildren()
    if len(children) > 0:
        for c in children:
            print(c.attrib)
            children = c.getchildren()
#mwah

In [44]:
for i in tree.getchildren()[1].getchildren()[0].getchildren()[0].getchildren():
    print(i.getchildren()[0].text)

73 van GOES, 29 september 1716.
Hoogedele Gestrenge Heer, Mijn Heer, Sooveel ik van
						tersijden hoor, want ik wil
Dit project en sou naa alle apparentie het hoff van
						Hanover niet aenstaen, vermits
Lange deliberatiën stellen de saak buyten haer geheel.
						Men heeft reets dagelijx
Robert Goes.
Coppenhagen, den 29

## Folia reader

We better parse this with the specialized Folia reader. Note, however, how letters are announced in the text. We may use this later on, but let's investigate this some more.

In [ ]:
# better do this with folia reader
import sys
!{sys.executable} -m pip install -U  folia

In [52]:
import folia.main as folia
import gzip, random
fn = os.path.join(basedir, random.choice(lst))
f=gzip.open(fn,'rb')
file_content=f.read()
#tree = open()
# parser = etree.XMLParser(recover=True)
# tree = etree.fromstring(file_content, parser)
doc = folia.Document(string=file_content)

# print (file_content)

In [62]:
doc.metadata.data

{'authorLevel1': 'A. Heinsius',
 'biblScope_page': '91-',
 'biblScope_volume': '11',
 'category': 'uitgave',
 'copyrightHolder': 'Huygens ING',
 'copyrightOwner': 'Huygens ING',
 'corpusProvenance': 'HuygensING-heinsius',
 'edition': '1',
 'editorLevel1': 'Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp',
 'editorLevel2': 'Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp',
 'factuality': 'non-fictie',
 'genre': 'egodocumenten',
 'ingestTime': '2017-06-24T08:05',
 'ipr': 'extern',
 'isbn': '905216018X',
 'language': 'nld',
 'medium': 'boek',
 'pid': 'INT_4cb30761-df19-41e1-8f01-af33c0c026db',
 'placePublication': "'s Gravenhage",
 'primaryLanguage': 'fr',
 'processingMethod': 'ongecorrigeerde OCR',
 'pubYear_from': '1990',
 'pubYear_to': '1990',
 'publisher': 'Instituut voor Nederlandse Geschiedenis',
 'resourceURI': 'http://resources.huygens.knaw.nl/retroboeken/heinsius/',
 'sourceID': 'heinsius:vol11:161',
 'statusText': 'geen vertaling',
 'subgenre': 'brieven',
 'subtitleLevel2': 'Deel 11, 1 augustus 1710 — 30 april 1711',
 'subtitleLevel3': 'Grote Serie 214',
 'textDay_from': '27',
 'textDay_to': '27',
 'textMonth_from': '8',
 'textMonth_to': '8',
 'textYear_from': '1710',
 'textYear_to': '1710',
 'titleLevel1': '161. aan Albemarle, 27-8-1710',
 'titleLevel2': 'De briefwisseling van Anthonie Heinsius 1702-1720',
 'titleLevel3': 'Rijks Geschiedkundige Publicatiën uitgegeven in opdracht van de minister van Onderwijs en Wetenschappen onder toezicht van de Rijkscommissie voor Vaderlandse Geschiedenis',
 'witnessYear_from': '1710',
 'witnessYear_to': '1710'}

In [462]:
doc.text()

"161. aan ALBEMARLE, 27 augustus 1710. Kopie', H.A. 1565.\n\nMylord, Mes occupations, principalement dans la dernier assemblé des Estats d’Hollande, m’ont empesché d’accuser celles que vous m’avez fait l’honneur de m’escrire. Je n’ay pas manqué pourtant d’y faire tout de réflexion qu’il m’a esté possible. Pour vos recommandations, Mess.s les Nobles ont eu assez de penchant pour le baron de Velp, mais ils n’y ont pas pu venir à bout, tant à cause de la dernière résolution qu’on ne doit pas sortir du régiment, si non par unanime des voix qu’à cause que la pluspart on cru que M.rGeorgin n’estoit pas tant incapable qu’on le débitoit et qu’ils n’y avoient pas assez de raisons pour le rendre malheureux. Pour Mons.r Otto, il a obtenu son but unanimement. Pour vostre frère, deux des députez m’ont escrit qu’il aura la gouvernement de Béthune, ainsi je comte que c’est une affair faite. Pour M.r Coljer, je seray toujours bien aise de luy faire service, mais je ne puis pas dire en quoy si longtemps que les affaires ne sont pas en délibération, car on a accoûtumé de concerter ensemble et ne s’engager pas auparavant. Vous avés escrit une lettre à Mess.s les Estats d’Hollande pour faire des collonel-commandant les bri- gadiers qui commandent les second bataillon Suisse, mais les Nobles qui y avoient consentis, ne sont pas suivi d’aucun membre, sur quoy on a proposé pour porter cette affaire à la Généralité et de conférer avec les Conceil d’Estat, ce qui a esté approuvé à peine. J’ay leu les projet de M.r Doph lequel je ne désapprouve pas, mais je ne voye pas où on trouvera les dépense des troupes estrangères qui y resteroient et qui n’y ont pas resté l’anné passé. Quand à la résolution touchant les commandants des places frontières, je me souviens d’avoir aussi assisté [à] la conférence qui est tenu sur ce sujet avec des députés du Conseil d’Etat, mais je ne croye pas que personne a eu en veue de chocquer qui que ce soit au monde. On a principalement réfléchi sur la différence qu’il i avoit entre le temps que ces places ont esté sous le roy de France et celuy-cy, que le roy de France avoit permis de tirer de gros gages et des émolumens extraordinaires outre que ses gouverneurs et commandans les avoient augmenté de temps en temps sous toute sorte de prétextes injuste, que le dit roy avoit le moyen de faire par là amenlieur2 ses finances; que nostre constitution estoit tout autre et que l’Estat ne chargoit jamais ses gouverneurs et commandants et que cependant on devoit avoir soin pour les finances, qu’ainsi il voudroit mieux d’en reigler les gages et attirer la reste pour les Estât; que par l’a on ostoient ausi tout la prétexte de surcharger le peuple. Pour vous dire la vérité, je croye ces motifs fort justes et raisonnable et puisque vous me faites l’honneur de me mander en amy mon avis, je vous dois dire que je ne croye pas que vous vous devriés y opposer, comme je ne croye pas ausi que personne du gouvernement qui eut cognoissance de cause vous pouroit conseiller autrement.\n\n160. 1. Kopie van een brief van Van Vrijbergen aan de griffier, 26 augustus 1710, aanwezig bij de brief: er zijn speculaties over verdere veranderingen in het ministerie.\n\n161. 1. Met aantekening van Heinsius in dorso: Lettre à mylord Albermarle, 27 août 1710.\n\nJe croye par l’expédient que vous avez proposé le différent avec le canton de Glaris sur la comp. dudit canton fini, mais par ce que M.r de Metral m’escrit et par la lettre cyjointe que j’ay receu depuis peu je ne le voye pas encore; je vous prie de me dire là-dessus vostre sentiment et d’estre persuadé que je suis etc.\n\nA la Haye, ce 27 août 1710.\n\nP. S. Mess.' Les députés de Bruxelles Van den Berg et Renswoude m’ont recommandé que je voulusse faire mon devoir afin que M.r Ernst Rudt d’Hans chanoin de Bruxelles fut élu doyen des chanoines de Tournay. Mylord duc m’a ausi escrit en sa faveur, comme plusieurs autres. On le dit fort attaché à l’Estat, mais on dit que ce doyence sans canonicat ne vaut que 1300 livres et qu’ainsi il ne pouroit pas subsister sans avoir l’un et l’autre. On y a pouroit réussir selon les reigles et comme je suis prié de vous vouloir recommander cette affaire pour le bien publicq, je n’ay pourtant pas voulu le faire sans le bon plaisir des Mess.5 les députez aux affaire estrangères, qui l’ont trouvé bon. Je vous prie donc si vous le trouverés bon ausi, d’y vouloir travailler. On dit qu’il a plusieurs chanoinnes de son costé; je ne sçay pas le méthode qu’on devra observer, mais il me semble qu’ils doivent faire une nomination. En tout cas on ne doit pas commettre l’Estat; c’est pourquoy si vous y prévoyés des obstacles, je vous prie de me le faire sçavoir."

In [148]:
print(doc) # accomplishes the same, but with a better printout.

161. aan ALBEMARLE, 27 augustus 1710. Kopie', H.A. 1565.

Mylord, Mes occupations, principalement dans la dernier assemblé des Estats d’Hollande, m’ont empesché d’accuser celles que vous m’avez fait l’honneur de m’escrire. Je n’ay pas manqué pourtant d’y faire tout de réflexion qu’il m’a esté possible. Pour vos recommandations, Mess.s les Nobles ont eu assez de penchant pour le baron de Velp, mais ils n’y ont pas pu venir à bout, tant à cause de la dernière résolution qu’on ne doit pas sortir du régiment, si non par unanime des voix qu’à cause que la pluspart on cru que M.rGeorgin n’estoit pas tant incapable qu’on le débitoit et qu’ils n’y avoient pas assez de raisons pour le rendre malheureux. Pour Mons.r Otto, il a obtenu son but unanimement. Pour vostre frère, deux des députez m’ont escrit qu’il aura la gouvernement de Béthune, ainsi je comte que c’est une affair faite. Pour M.r Coljer, je seray toujours bien aise de luy faire service, mais je ne puis pas dire en quoy si longtemps que les affaires ne sont pas en délibération, car on a accoûtumé de concerter ensemble et ne s’engager pas auparavant. Vous avés escrit une lettre à Mess.s les Estats d’Hollande pour faire des collonel-commandant les bri- gadiers qui commandent les second bataillon Suisse, mais les Nobles qui y avoient consentis, ne sont pas suivi d’aucun membre, sur quoy on a proposé pour porter cette affaire à la Généralité et de conférer avec les Conceil d’Estat, ce qui a esté approuvé à peine. J’ay leu les projet de M.r Doph lequel je ne désapprouve pas, mais je ne voye pas où on trouvera les dépense des troupes estrangères qui y resteroient et qui n’y ont pas resté l’anné passé. Quand à la résolution touchant les commandants des places frontières, je me souviens d’avoir aussi assisté [à] la conférence qui est tenu sur ce sujet avec des députés du Conseil d’Etat, mais je ne croye pas que personne a eu en veue de chocquer qui que ce soit au monde. On a principalement réfléchi sur la différence qu’il i avoit entre le temps que ces places ont esté sous le roy de France et celuy-cy, que le roy de France avoit permis de tirer de gros gages et des émolumens extraordinaires outre que ses gouverneurs et commandans les avoient augmenté de temps en temps sous toute sorte de prétextes injuste, que le dit roy avoit le moyen de faire par là amenlieur2 ses finances; que nostre constitution estoit tout autre et que l’Estat ne chargoit jamais ses gouverneurs et commandants et que cependant on devoit avoir soin pour les finances, qu’ainsi il voudroit mieux d’en reigler les gages et attirer la reste pour les Estât; que par l’a on ostoient ausi tout la prétexte de surcharger le peuple. Pour vous dire la vérité, je croye ces motifs fort justes et raisonnable et puisque vous me faites l’honneur de me mander en amy mon avis, je vous dois dire que je ne croye pas que vous vous devriés y opposer, comme je ne croye pas ausi que personne du gouvernement qui eut cognoissance de cause vous pouroit conseiller autrement.

160. 1. Kopie van een brief van Van Vrijbergen aan de griffier, 26 augustus 1710, aanwezig bij de brief: er zijn speculaties over verdere veranderingen in het ministerie.

161. 1. Met aantekening van Heinsius in dorso: Lettre à mylord Albermarle, 27 août 1710.

Je croye par l’expédient que vous avez proposé le différent avec le canton de Glaris sur la comp. dudit canton fini, mais par ce que M.r de Metral m’escrit et par la lettre cyjointe que j’ay receu depuis peu je ne le voye pas encore; je vous prie de me dire là-dessus vostre sentiment et d’estre persuadé que je suis etc.

A la Haye, ce 27 août 1710.

P. S. Mess.' Les députés de Bruxelles Van den Berg et Renswoude m’ont recommandé que je voulusse faire mon devoir afin que M.r Ernst Rudt d’Hans chanoin de Bruxelles fut élu doyen des chanoines de Tournay. Mylord duc m’a ausi escrit en sa faveur, comme plusieurs autres. On le dit fort attaché à l’Estat, mais on dit que ce doyence sans canonicat ne vaut que 1300 livres et qu’ainsi il ne pouroit pas subsister sans avoir l’un et l’autre. On y a pouroit réussir selon les reigles et comme je suis prié de vous vouloir recommander cette affaire pour le bien publicq, je n’ay pourtant pas voulu le faire sans le bon plaisir des Mess.5 les députez aux affaire estrangères, qui l’ont trouvé bon. Je vous prie donc si vous le trouverés bon ausi, d’y vouloir travailler. On dit qu’il a plusieurs chanoinnes de son costé; je ne sçay pas le méthode qu’on devra observer, mais il me semble qu’ils doivent faire une nomination. En tout cas on ne doit pas commettre l’Estat; c’est pourquoy si vous y prévoyés des obstacles, je vous prie de me le faire sçavoir.

In [63]:
doc.annotations

[(0,
  'https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/text.foliaset.ttl'),
 (19,
  'https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/phon.foliaset.ttl'),
 (25, 'unknown'),
 (37, 'unknown'),
 (38, 'unknown'),
 (3, 'unknown'),
 (17, 'unknown'),
 (35, 'unknown'),
 (2, 'unknown'),
 (34,
  'http://raw.github.com/proycon/folia/master/setdefinitions/iso639_3.foliaset'),
 (1, 'tokconfig-nld'),
 (1, 'tokconfig-fra'),
 (33,
  'https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/nederlab-metrics.foliaset.ttl'),
 (11,
  'https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/int_lemmaid_withcompounds.foliaset.ttl'),
 (11,
  'https://raw.githubusercontent.com/proycon/folia/master/setdefinitions/int_lemmatext_withcompounds.foliaset.ttl'),
 (10, 'http://ilk.uvt.nl/folia/sets/frog-mbpos-cgn'),
 (11, 'http://ilk.uvt.nl/folia/sets/frog-mblem-nl'),
 (16, 'http://ilk.uvt.nl/folia/sets/frog-ner-nl'),
 (29, 'ErwinKomen-NEL')]

#### Comments

Some notes on the meta data. There are a number of misidentifications, including Heinsius as the main author (it was his correspondence, but they include many letters written by others). Also the metadata are a mix of the book level metadata and some page level specific data. The annotations are  mostly. This page contains one letter, in french which is correctly identified. Let's find out how this goes with several letters on a page. We could get all metadata from the files, but first I want to know some more about the structure. There is no simple way to leaf through the documents, so let's get a sample from them

for word in doc.words():
    try:
        pos = word.annotation(folia.PosAnnotation, 'http://somewhere/CGN')
        lemma = word.annotation(folia.LemmaAnnotation)
        print("Word: ", word)
        print("ID: ", word.id)
        print("PoS-tag: " , pos.cls)
        print("PoS Annotator: ", pos.annotator)
        print("Lemma-tag: " , lemma.cls)
    except folia.NoSuchAnnotation:
        pass

from folia import fql

query = fql.Query('SELECT w WHERE text = "162. "')
for word in query(doc):
    print(word)

In [ ]:
indocs =

qs

In [467]:
fls = random.choices(lst, k=30)
rdata = []
for f in fls:
    fn = os.path.join(basedir, f)
    f=gzip.open(fn,'rb')
    file_content=f.read()
    doc = folia.Document(string=file_content)
    record = doc.metadata.data
    record['filename'] = fn
    rdata.append(record)

In [469]:
sample_brieven = pd.DataFrame().from_records(rdata)

In [471]:
sample_brieven.iloc[0].filename

'/Users/rikhoekstra/develop/heinsius_linked/HuygensING-heinsius-1-1_b1acd4ce-16a4-4d2a-afa1-1d2bb32e8c27.folia.xml.gz'

In [474]:
f=gzip.open('/Users/rikhoekstra/develop/heinsius_linked/HuygensING-heinsius-1-1_b1acd4ce-16a4-4d2a-afa1-1d2bb32e8c27.folia.xml.gz','rb')
file_content=f.read()
doc = folia.Document(string=file_content)
print(doc.text())

950. van SAUNIERE DE L’HERMITAGE, 6 oktober 1 702. Eigenh. orig. H.A. 792.

Shovell is de 4e oktober in zee gestoken om de zilvervloot van Châteaurenault te onderscheppen. Men hoopt dat de zilvervloot of nietsvermoedend naar Cadiz zal zeilen, of door Shovell ontmoet zal worden. Men heeft weinig zekerheid over de situatie bij Cadiz. De Fransen hebben op New F oundland een Engelse nederzetting overvallen.

Je me trouvai il y a 2 jours dans une assemblée où estoit l’envoyé de Portugal1 où il vouloit faire entendre que les Espagnols estoient encore en estât de faire de grand efforts pour repousser les attaques de la flote. Il dit qu’il y avoit de grandes dispositions à trouver beaucoup d’argent et qu’il y avoit une grande différance à l’éléver par taxe ou à ne porter volontairement; que de la première manière il seroit rare en Espagne, mais qu’à l’heure présente les Espagnols alloient au devant des nécessités; que le clergé, qui estoit le principal, marquoit un zelle admirable et qu’on luy mandoit que l’archevesque de Séville2 avoit donné une année de son revenu, le chapitre dix mil pistoles et q’une infinité d’autres en avoient fait autant et cet envoyé en toutes occasions veust aussi donner des marques de zon zelie pour la France. L’amb. de Vénise34 estoit présent et l’envoyé de Florance . Uit Londen.

5. Adolf Hendrik van Rechteren (1656-1731), heer van Almelo, 1705 graaf des H.R.R., lid Ridderschap van Overijsel sinds 1680, drost van Vollenhove 1701, drost van Salland en als zodanig president van de Landdag van Overijsel sinds 1705, gedeputeerde ter Staten-Generaal, gedeputeerde te velde 1702 en 1703, extraordinaris envoyé naar de Kreitsen van het Duitse Rijk en verscheidene Duitse vorsten 1703, naar Wenen 1705, afgevaardigde op het vredescongres te Utrecht 1712, bij de onderhandelingen over de barrière te Antwerpen 1714-1715. NNBW, II, k. 1174; Graswinckel, „A.H. van Rechteren”. Overijselse Portretten, p. 95 vlg.

1. Dom Luis da Cunha.

950.

This is nice, as it shows that in this resource the pages were cut up into letters. We can use them later on. Let's make a complete dataframe from the files then.

In [489]:
already_parsed = list(brieven_data.filename)
len(already_parsed)

14056

In [490]:
for f in lst:
    fn = os.path.join(basedir, f)
    if '.gz' in fn:
        if fn not in already_parsed:
            f=gzip.open(fn,'rb')
            file_content=f.read()
            doc = folia.Document(string=file_content)
            record = doc.metadata.data
            record['filename'] = fn
            rdata.append(record)

In [493]:
len(brieven_data)

17957

In [498]:
brieven_data = pd.DataFrame().from_records(rdata)
brieven_data = brieven_data.drop_duplicates()
brieven_data

,authorLevel1,biblScope_page,biblScope_volume,category,copyrightHolder,copyrightOwner,corpusProvenance,edition,editorLevel1,editorLevel2,...,titleLevel1,titleLevel2,titleLevel3,witnessDay_from,witnessDay_to,witnessMonth_from,witnessMonth_to,witnessYear_from,witnessYear_to,filename
0,Sauniere de l'Hermitage,463-,1,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,Dr. A.J. Veenendaal jr.,Dr. A.J. Veenendaal jr.,...,"950. van Sauniere de l'Hermitage, 6-10-1702",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,6,6,10,10,1702,1702,/Users/rikhoekstra/develop/heinsius_linked/Huy...
1,Ouwerkerk,523-,6,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,Dr. A.J. Veenendaal jr.,Dr. A.J. Veenendaal jr.,...,"1043. van Ouwerkerk, 8-9-1707",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,8,8,9,9,1707,1707,/Users/rikhoekstra/develop/heinsius_linked/Huy...
2,E. Pesters,598-,13,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,"Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp","Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp",...,"937. van E. Pesters, 1-8-1712",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,1,1,8,8,1712,1712,/Users/rikhoekstra/develop/heinsius_linked/Huy...
3,Schmettau,457-,9,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,Dr. A.J. Veenendaal jr.,Dr. A.J. Veenendaal jr.,...,"969. van Schmettau, 26-11-1709",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,26,26,11,11,1709,1709,/Users/rikhoekstra/develop/heinsius_linked/Huy...
4,Buys,622-,14,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,"Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp","Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp",...,"919. van Buys, 22-3-1713",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,22,22,3,3,1713,1713,/Users/rikhoekstra/develop/heinsius_linked/Huy...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17978,A. Heinsius,425-,7,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,Dr. A.J. Veenendaal jr.,Dr. A.J. Veenendaal jr.,...,"914. aan Van Rechteren-Almelo, 1-8-1708",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,NaN,NaN,NaN,NaN,1708,1708,/Users/rikhoekstra/develop/heinsius_linked/Huy...
17979,A. Heinsius,266-,10,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,"Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp","Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp",...,"508. aan Buys, 19-4-1710",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,NaN,NaN,NaN,NaN,1710,1710,/Users/rikhoekstra/develop/heinsius_linked/Huy...
17980,N. Clignet,12-,7,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,Dr. A.J. Veenendaal jr.,Dr. A.J. Veenendaal jr.,...,"25. van N. Clignet, 8-1-1708",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,8,8,1,1,1708,1708,/Users/rikhoekstra/develop/heinsius_linked/Huy...
17981,Sauniere de l'Hermitage,14-,19,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,"Dr. A.J. Veenendaal jr., Mw. M.T.A. Schouten","Dr. A.J. Veenendaal jr., Mw. M.T.A. Schouten",...,"22. van Sauniere de l'Hermitage, 25-10-1718",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,25,25,10,10,1718,1718,/Users/rikhoekstra/develop/heinsius_linked/Huy...
17982,Ph.J. van Borssele van der Hooghe,652-,14,uitgave,Huygens ING,Huygens ING,HuygensING-heinsius,1,"Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp","Dr. A.J. Veenendaal jr., Mw. C. Hogenkamp",...,"966. van Ph.J. van Borssele van der Hooghe, 31...",De briefwisseling van Anthonie Heinsius 1702-1720,Rijks Geschiedkundige Publicatiën uitgegeven i...,31,31,3,3,1713,1713,/Users/rikhoekstra/develop/heinsius_linked/Huy...

In [501]:
fn = os.path.join('/Users/rikhoekstra/Downloads/heinsius_brieven/', 'heinsius_brieven_data.csv')

My notebook did not like that much, so let's write this to the file system and not regenerate them again...

In [502]:
brieven_data.to_csv(fn, sep='\t')

### correspondents

In the meantime we put the database of correspondents in mysql and we want to connect them with the deputies from the RAA.

In [ ]:
import pandas as pd
from sqlalchemy import text

In [ ]:
qs = "SELECT * FROM heinsius.PersonName join heinsius.NLPerson on heinsius.PersonName.personNameID=heinsius.NLPerson.preferredNameID"

In [79]:
query= '''SELECT raa_new.functie.naam as functienaam, 
	   raa_new.instelling.naam as college,
       raa_new.persoon.searchable as regent,
       raa_new.persoon.voornaam,
       raa_new.persoon.geslachtsnaam,
       raa_new.persoon.tussenvoegsel,
       raa_new.persoon.geboortedatum,
       raa_new.persoon.overlijdensdatum,
       raa_new.aanstelling.*
FROM raa_new.aanstelling 
JOIN raa_new.functie on raa_new.aanstelling.functie_id = raa_new.functie.id
JOIN raa_new.instelling on raa_new.aanstelling.instelling_id = raa_new.instelling.id
JOIN raa_new.persoon on raa_new.aanstelling.persoon_id = raa_new.persoon.id
WHERE raa_new.instelling.naam LIKE "%Staten-Generaal%"
order by  raa_new.aanstelling.tot;'''

con = "mysql+pymysql://rik:X0chi@localhost/raa_new"

In [82]:
df_deputies = pd.read_sql(con=con, sql=text(query), parse_dates={'van':None,
                                                        'tot':None})

In [83]:
df_heinsius = pd.read_sql(con=con, sql=text(qs))

In [86]:
df_heinsius.merge(df_deputies, left_on=["lastName", "firstName"], right_on=["geslachtsnaam", "voornaam"])

,personNameID,personID,lastName,firstName,infixes,firstNameFull,prefixTitle,additionalTitle,organisationName,nederlabID,...,old_id,old_idcollege,old_idfunctie,old_idregent,old_lokaal,old_provinciaal,old_regio,old_stand,old_vertegenwoordigend,periode
0,81ca5418-0590-6724-a732-1b31d671628d,0114add4-9790-3ae6-80b5-1aa41ea0b0f6,Cuper,Gisbert,,Gisbert,,,,0114add4-9790-3ae6-80b5-1aa41ea0b0f6,...,republiek_9506,republiek_27,republiek_8,republiek_3295,republiek_28,republiek_9,republiek_0,republiek_0,republiek_0,1
1,f44d13f0-f8bf-c588-3858-be1ca0f530bf,06a9bc10-9af9-d8f7-1776-34ef9e91aedf,Burch,Johan,van der,Johan,Mr.,heer van Naaldwijk en Sliedrecht,,06a9bc10-9af9-d8f7-1776-34ef9e91aedf,...,republiek_532,republiek_27,republiek_8,republiek_253,republiek_2,republiek_3,republiek_nan,republiek_nan,republiek_0,1
2,a049f3b6-982d-1f92-0394-f8febbd1ab2d,d1cb67fb-b065-9e12-b697-80a72db8c194,Burch,Johan,van der,Johan,Mr.,,,d1cb67fb-b065-9e12-b697-80a72db8c194,...,republiek_532,republiek_27,republiek_8,republiek_253,republiek_2,republiek_3,republiek_nan,republiek_nan,republiek_0,1
3,c3983234-aacb-3771-d3ea-f462eaa110f3,3d4d4aa1-cafd-6c35-f477-844933bc8083,Kemp,Pieter,,Pieter,Mr.,heer van Moermond,,3d4d4aa1-cafd-6c35-f477-844933bc8083,...,republiek_11899,republiek_27,republiek_8,republiek_4055,republiek_21,republiek_5,republiek_0,republiek_0,republiek_0,1
4,0a8ae586-6fff-e1d5-7c22-a0793c4de76a,4c5896d2-4fad-74e7-fad0-006a59119df4,Essen,Johan,van,Johan,Mr.,,,4c5896d2-4fad-74e7-fad0-006a59119df4,...,republiek_19892,republiek_27,republiek_80,republiek_6300,republiek_44,republiek_8,republiek_11,republiek_0,republiek_0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,a3c5fe65-8c27-c923-8c42-cdc45101b2c7,f4c884cd-3a2a-792f-299e-f1475da1beb5,Lintelo,Christiaan Carel,van,Christiaan Carel,,,,f4c884cd-3a2a-792f-299e-f1475da1beb5,...,republiek_19901,republiek_27,republiek_8,republiek_6304,republiek_40,republiek_8,republiek_11,republiek_0,republiek_0,1
77,a3c5fe65-8c27-c923-8c42-cdc45101b2c7,f4c884cd-3a2a-792f-299e-f1475da1beb5,Lintelo,Christiaan Carel,van,Christiaan Carel,,,,f4c884cd-3a2a-792f-299e-f1475da1beb5,...,republiek_20108,republiek_27,republiek_8,republiek_6304,republiek_53,republiek_8,republiek_11,republiek_0,republiek_0,1
78,431a9f1d-afd2-99f3-4170-997254ec4a92,f9b52021-c213-1c1d-656c-aa63ff1da494,Heteren,Leonard,van,Leonard,,,,f9b52021-c213-1c1d-656c-aa63ff1da494,...,republiek_19890,republiek_27,republiek_8,republiek_6298,republiek_47,republiek_8,republiek_10,republiek_0,republiek_0,1
79,431a9f1d-afd2-99f3-4170-997254ec4a92,f9b52021-c213-1c1d-656c-aa63ff1da494,Heteren,Leonard,van,Leonard,,,,f9b52021-c213-1c1d-656c-aa63ff1da494,...,republiek_19959,republiek_27,republiek_8,republiek_6298,republiek_47,republiek_8,republiek_10,republiek_0,republiek_0,1
80,431a9f1d-afd2-99f3-4170-997254ec4a92,f9b52021-c213-1c1d-656c-aa63ff1da494,Heteren,Leonard,van,Leonard,,,,f9b52021-c213-1c1d-656c-aa63ff1da494,...,republiek_19991,republiek_27,republiek_8,republiek_6298,republiek_47,republiek_8,republiek_10,republiek_0,republiek_0,1

In [504]:
depu = pd.read_parquet("/Users/rikhoekstra/Downloads/consolidated_extended_raa.parquet")

In [503]:
correspondents_in_raa = df_heinsius.merge(depu, left_on=["lastName", "firstName"], right_on=["geslachtsnaam", "voornaam"])

#### Comment

These are the correspondents who also are in the RAA

## Heinsius index

The correspondents is only a subset of the names in the Heinsius edition. The bulk is in the index

In [505]:
heinsius_dir = "/Users/rikhoekstra/develop/namenindex/heinsius/out/"

In [187]:
import os
heinsius_names = []
fls = [f for f in os.listdir(heinsius_dir) if '.xml' in f]
for f in fls:
    item = {}
    with open(os.path.join(heinsius_dir, f)) as infl:
        n = os.path.splitext(f)[0]
        item['nr'] = n
        ndoc = etree.parse(infl)
        p = [r for r in ndoc.getroot().getchildren() if r.tag == 'person'][0]
        persname = [r for r in p.getchildren() if r.tag == 'persName'][0]
        name = persname.text
        item['name'] = name
        b = [r for r in ndoc.getroot().getchildren() if r.tag == 'biography'][0]
        bc = b.getchildren()
        if len(bc)>0:
            text = bc[0].text
        else:
            text = ''
        item['text'] = text
        heinsius_names.append(item)

In [173]:
p = [r for r in ndoc.getroot().getchildren() if r.tag == 'person'][0]

In [174]:
b = [r for r in ndoc.getroot().getchildren() if r.tag == 'biography'][0]

In [175]:
persname = [r for r in p.getchildren() if r.tag == 'persName'][0]

In [177]:
persname.text

'Adolf, Vorst van Nassau-Siegen'

In [181]:
b.getchildren()[0].text

'(1680-1722) Vorst sinds 1691, vertegenwoordiger van de protestantse tak van het  huis Nassau-Siegen. Wilhelm Hyacinth, vorst van Nassau-Siegen, was de rooms-katholieke  vorst. <I>Europäische Stammtafeln</I>, I, T.117.'

In [195]:
import html
df_nms = pd.DataFrame.from_records(heinsius_names)
df_nms['text_unescaped'] = df_nms.text.apply(lambda x: html.unescape(x)) # we leave the unescaped text for possible searching
df_nms

,nr,name,text,text_unescaped
0,5848,"Sheffield, John, Markies van Normanby, Hertog ...",(1648-1721) Engels edelman; 1694 markies van N...,(1648-1721) Engels edelman; 1694 markies van N...
1,5690,"Scheltinga, Martinus van",(1666-1742) Grietman van Schoterland 1692-1742...,(1666-1742) Grietman van Schoterland 1692-1742...
2,0930,"Brieux, François Moissant de",(&#134; 1727) Officier in Nederlandse dienst; ...,(† 1727) Officier in Nederlandse dienst; 1711 ...
3,6399,"Tursi, N",N. hertog van. Genuees edelman in dienst van ...,N. hertog van. Genuees edelman in dienst van ...
4,1390,"Coeuvres, Maarschalk de, zie Estrées, Victor-M...",,
...,...,...,...,...
6894,0929,"Brienne, Simon de",(&#134; 1707) Kamerdienaar en barbier van Will...,(† 1707) Kamerdienaar en barbier van Willem II...
6895,6380,"Tscharner, Niklaus",(1650-1737) [geschreven aan Heinsius] Zwiters...,(1650-1737) [geschreven aan Heinsius] Zwiters...
6896,5689,"Schellingwouw, Alida van",(&#134; 1717) Vrouwe van Poelgeest en Koudeker...,(† 1717) Vrouwe van Poelgeest en Koudekerk; si...
6897,5851,"Sheremetov, Michael",Zoon van de voorgaande; officier; 1711 gevolma...,Zoon van de voorgaande; officier; 1711 gevolma...
6898,4597,"Nassau-Siegen, Prins van, zie Alexis Anton Chr...","- prinses van, zie Maria Anna Josepha. - vorst...","- prinses van, zie Maria Anna Josepha. - vorst..."

In [342]:
# this regex tries to get the living years from the description
import re
pat1 = re.compile("(?P<year1>(1+[0-9]{3})?)(?P<hyphen>[†-])?(?P<year2>1+[0-9]{3})+")

def match_years(x):
    res = pat1.search(x)
    if res:
        res = res.groupdict()
    return res

In [506]:
#put the year in the data frame
pd.concat([df_nms, df_nms.text_unescaped.apply(lambda x: match_years(x)).apply(pd.Series)], axis=1)

,nr,name,text,text_unescaped,years,year1,hyphen,year2
0,5848,"Sheffield, John, Markies van Normanby, Hertog ...",(1648-1721) Engels edelman; 1694 markies van N...,(1648-1721) Engels edelman; 1694 markies van N...,"{'year1': '1648', 'hyphen': '-', 'year2': '1721'}",1648,-,1721
1,5690,"Scheltinga, Martinus van",(1666-1742) Grietman van Schoterland 1692-1742...,(1666-1742) Grietman van Schoterland 1692-1742...,"{'year1': '1666', 'hyphen': '-', 'year2': '1742'}",1666,-,1742
2,0930,"Brieux, François Moissant de",(&#134; 1727) Officier in Nederlandse dienst; ...,(† 1727) Officier in Nederlandse dienst; 1711 ...,"{'year1': '', 'hyphen': None, 'year2': '1727'}",,None,1727
3,6399,"Tursi, N",N. hertog van. Genuees edelman in dienst van ...,N. hertog van. Genuees edelman in dienst van ...,None,NaN,NaN,NaN
4,1390,"Coeuvres, Maarschalk de, zie Estrées, Victor-M...",,,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
6894,0929,"Brienne, Simon de",(&#134; 1707) Kamerdienaar en barbier van Will...,(† 1707) Kamerdienaar en barbier van Willem II...,"{'year1': '', 'hyphen': None, 'year2': '1707'}",,None,1707
6895,6380,"Tscharner, Niklaus",(1650-1737) [geschreven aan Heinsius] Zwiters...,(1650-1737) [geschreven aan Heinsius] Zwiters...,"{'year1': '1650', 'hyphen': '-', 'year2': '1737'}",1650,-,1737
6896,5689,"Schellingwouw, Alida van",(&#134; 1717) Vrouwe van Poelgeest en Koudeker...,(† 1717) Vrouwe van Poelgeest en Koudekerk; si...,"{'year1': '', 'hyphen': None, 'year2': '1717'}",,None,1717
6897,5851,"Sheremetov, Michael",Zoon van de voorgaande; officier; 1711 gevolma...,Zoon van de voorgaande; officier; 1711 gevolma...,"{'year1': '', 'hyphen': None, 'year2': '1711'}",,None,1711
6898,4597,"Nassau-Siegen, Prins van, zie Alexis Anton Chr...","- prinses van, zie Maria Anna Josepha. - vorst...","- prinses van, zie Maria Anna Josepha. - vorst...",None,NaN,NaN,NaN

In [344]:
df_nms

,nr,name,text,text_unescaped,years
0,5848,"Sheffield, John, Markies van Normanby, Hertog ...",(1648-1721) Engels edelman; 1694 markies van N...,(1648-1721) Engels edelman; 1694 markies van N...,"{'year1': '1648', 'hyphen': '-', 'year2': '1721'}"
1,5690,"Scheltinga, Martinus van",(1666-1742) Grietman van Schoterland 1692-1742...,(1666-1742) Grietman van Schoterland 1692-1742...,"{'year1': '1666', 'hyphen': '-', 'year2': '1742'}"
2,0930,"Brieux, François Moissant de",(&#134; 1727) Officier in Nederlandse dienst; ...,(† 1727) Officier in Nederlandse dienst; 1711 ...,"{'year1': '', 'hyphen': None, 'year2': '1727'}"
3,6399,"Tursi, N",N. hertog van. Genuees edelman in dienst van ...,N. hertog van. Genuees edelman in dienst van ...,None
4,1390,"Coeuvres, Maarschalk de, zie Estrées, Victor-M...",,,None
...,...,...,...,...,...
6894,0929,"Brienne, Simon de",(&#134; 1707) Kamerdienaar en barbier van Will...,(† 1707) Kamerdienaar en barbier van Willem II...,"{'year1': '', 'hyphen': None, 'year2': '1707'}"
6895,6380,"Tscharner, Niklaus",(1650-1737) [geschreven aan Heinsius] Zwiters...,(1650-1737) [geschreven aan Heinsius] Zwiters...,"{'year1': '1650', 'hyphen': '-', 'year2': '1737'}"
6896,5689,"Schellingwouw, Alida van",(&#134; 1717) Vrouwe van Poelgeest en Koudeker...,(† 1717) Vrouwe van Poelgeest en Koudekerk; si...,"{'year1': '', 'hyphen': None, 'year2': '1717'}"
6897,5851,"Sheremetov, Michael",Zoon van de voorgaande; officier; 1711 gevolma...,Zoon van de voorgaande; officier; 1711 gevolma...,"{'year1': '', 'hyphen': None, 'year2': '1711'}"
6898,4597,"Nassau-Siegen, Prins van, zie Alexis Anton Chr...","- prinses van, zie Maria Anna Josepha. - vorst...","- prinses van, zie Maria Anna Josepha. - vorst...",None

In [341]:
df_nms.loc[(df_nms.years.notna()) & (df_nms.years.str.contains('-'))]

,nr,name,text,text_unescaped,years
0,5848,"Sheffield, John, Markies van Normanby, Hertog ...",(1648-1721) Engels edelman; 1694 markies van N...,(1648-1721) Engels edelman; 1694 markies van N...,1648-1721
1,5690,"Scheltinga, Martinus van",(1666-1742) Grietman van Schoterland 1692-1742...,(1666-1742) Grietman van Schoterland 1692-1742...,1666-1742
12,5684,"Schaub, Lukas",(1690-1758) Zwitser geboortig uit Basel; 1712 ...,(1690-1758) Zwitser geboortig uit Basel; 1712 ...,1690-1758
14,2869,"Hastings, Theophilus, Graaf van Huntingdon",(1650-1701) Getrouwd met Frances Leveson Fowler.,(1650-1701) Getrouwd met Frances Leveson Fowler.,1650-1701
16,0918,"Breuner, Max Ludwig, Graaf",(1643-1706) Keizerlijk General Kriegskommissar...,(1643-1706) Keizerlijk General Kriegskommissar...,1643-1706
...,...,...,...,...,...
6875,5892,"Siöblad, Erik, Friherre",(1647-1725) Zweeds marine-officier; admiraal e...,(1647-1725) Zweeds marine-officier; admiraal e...,1647-1725
6876,4554,"Muyssart, Abraham",(1676-1724) [geschreven aan Heinsius] [beantw...,(1676-1724) [geschreven aan Heinsius] [beantw...,1676-1724
6877,2125,"Everswijn, Johan",(1651-1718) Haarlems regent.,(1651-1718) Haarlems regent.,1651-1718
6889,2694,"Gualtieri, Filippo Antonio",(1660-1728) Titulair aartsbisschop van Athene;...,(1660-1728) Titulair aartsbisschop van Athene;...,1660-1728
6895,6380,"Tscharner, Niklaus",(1650-1737) [geschreven aan Heinsius] Zwiters...,(1650-1737) [geschreven aan Heinsius] Zwiters...,1650-1737

## Connect to REPUBLIC index

In [216]:
import gzip
f='/Users/rikhoekstra/surfdrive/Shared/REPUBLIC/indices/index_entries-3763-3804.csv.gz'
indexdf=pd.read_csv(f, compression='gzip', header=0, sep='\t')
indexdf

,lemma,main_term,text,first_line_id,first_line_scan_id,first_line_page_id,first_line_column_id,last_line_id,last_line_scan_id,last_line_page_id,last_line_column_id
0,nee Winter quartieren,nee,"nee Winter quartieren, 918.",NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...
1,nee Winter quartieren,nee,aerte tifthop van Gran Brief van felicitatie o...,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...
2,albadie,albadie,"albadie, Collonel, om tot Brigadier aengeselt ...",NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...
3,albadie,albadie,"verfoeekende het Commande- ment van Roermonde,...",NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...
4,Ackema Commandeur tot Tseroort,Ackema,"Ackema Commandeur tot Tseroort , 90.",NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...,NL-HaNA_1.01.02_3763_0626,NL-HaNA_1.01.02_3763_0626-page-1251,NL-HaNA_1.01.02_3763_0626-column-2471-1318-894...
...,...,...,...,...,...,...,...,...,...,...,...
145980,Zouner,Zouner,Zouner om gratificatie voor de Kerk te Hom- bu...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...
145981,Zwitzerse Cantons,Zwitzerse,"Zwitzerse Cantons, klagbten van de Capi- teyne...",NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...
145982,Zwitzerse Cantons,Zwitzerse,Missive van bet Ganton Zurich xwee- gens de re...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...
145983,Zwitzerse Cantons,Zwitzerse,Misive van den Raad van Schaf- bausen weegens ...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...
145984,Zwitzerse Cantons,Zwitzerse,item van Appenzel. 763.,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...,NL-HaNA_1.01.02_3804_0043,NL-HaNA_1.01.02_3804_0043-page-84,NL-HaNA_1.01.02_3804_0043-column-1355-382-938-...

In [220]:
df_nms.loc[df_nms.name.str.contains('A?kem.*', regex=True)]

Empty DataFrame
Columns: [nr, name, text, text_unescaped]
Index: []

In [221]:
# better match on the unique main terms
uniqueterms = indexdf.main_term.unique()

In [222]:
len(uniqueterms)

15018

In [236]:
df_uterms = pd.DataFrame(uniqueterms, columns=['term'])
df_uterms.loc[df_uterms.term.notna()]

                 term
0                 nee
1             albadie
2              Ackema
3       aômirauteyten
4      aaniraliteyten
...               ...
15013        Wildeman
15014           Wobma
15015      Wurtsburgh
15016          Zouner
15017       Zwitzerse

[15017 rows x 1 columns]

In [224]:
# this is from https://stackoverflow.com/questions/13636848/is-it-possible-to-do-fuzzy-match-merge-with-python-pandas
import difflib 

def fuzzy_merge(df1, df2, left_on, right_on, how='inner', cutoff=0.6):
    df_other= df2.copy()
    df_other[left_on] = [get_closest_match(x, df1[left_on], cutoff) 
                         for x in df_other[right_on]]
    return df1.merge(df_other, on=left_on, how=how)


def get_closest_match(x, other, cutoff):
    matches = difflib.get_close_matches(x, other, cutoff=cutoff, n=1)
    return matches[0] if matches else None

# def get_closest_match(x, other, cutoff):
#     matches = score_levenshtein_similarity_ratio(x, other)
#     return matches if matches else None

In [ ]:
name_merge = fuzzy_merge(df_nms, df_uterms.loc[df_uterms.term.notna()], left_on='name', right_on='term', cutoff=0.7)

In [288]:
index_w_heinsius = name_merge.merge(indexdf, left_on='term', right_on='main_term')

In [246]:
len(name_merge)

962

In [252]:
correspondents_merge = fuzzy_merge(df_heinsius, df_uterms.loc[df_uterms.term.notna()], left_on='lastName', right_on='term', cutoff=0.9)

In [257]:
correspondents_merge.loc[correspondents_merge.duplicated()]

Empty DataFrame
Columns: [personNameID, personID, lastName, firstName, infixes, firstNameFull, prefixTitle, additionalTitle, organisationName, nederlabID, editorialCode, versionID, sourceRef, sourceCollection, preferredNameID, dateOfBirthDayMonth, yearOfBirthMin, yearOfBirthMax, yearOfBirthApprox, yearOfBirthLabel, placeOfBirthID, placeOfBirth, dateOfDeathDayMonth, yearOfDeathMin, yearOfDeathMax, yearOfDeathApprox, yearOfDeathLabel, placeOfDeathID, placeOfDeath, gender, ingestTime, updateTime, lastEditedBy, modificationTime, editorialNote, isThesaurusElement, inThesaurusAs, term]
Index: []

[0 rows x 38 columns]

In [250]:
from fuzzy_search.fuzzy_string import score_levenshtein_similarity_ratio

In [251]:
groupedcorrespondents_merge.groupby('personID')

In [259]:
name_merge.to_csv('/Users/rikhoekstra/Downloads/main_term_merge_heinsius_index.csv', sep='\t', compression='gzip')

In [260]:
index_w_heinsius.to_csv('/Users/rikhoekstra/Downloads/index_merge_heinsius_index.csv.gz', sep='\t', compression='gzip')

In [261]:
from republic.model.inventory_mapping import get_inventory_by_num # so that we can date the index terms

In [273]:
indexdf['invnr'] = indexdf.first_line_column_id.str.split('_', expand=True)[2]

In [275]:
indexdf.invnr = indexdf.invnr.astype('float', errors='ignore')

In [287]:
indexdf['year'] = indexdf.invnr.apply(lambda x: get_inventory_by_num(x).get('year'))

In [279]:
get_inventory_by_num(3804)

{'inventory_num': 3804,
 'inventory_uuid': '278358e3-85df-45df-a4c3-0043ae8e62fa',
 'period': ['1749-01-01', '1749-12-31'],
 'series_name': 'NL-HaNA_1.01.02',
 'series_uuid': '6e8998f6-cc66-43b9-92ae-85423ed66958',
 'year': 1749}

In [294]:
index_w_heinsius_1703_1740 = index_w_heinsius[index_w_heinsius.year.isin(list(range(1703, 1740)))]

In [295]:
index_w_heinsius_1703_1740.to_csv('/Users/rikhoekstra/Downloads/index_merge_heinsius_index_1703_1740.csv.gz', sep='\t', compression='gzip')

In [298]:
uniqueterms2 = indexdf.loc[indexdf.year.isin(list(range(1703, 1740)))].main_term.unique()

In [301]:
len(set(uniqueterms) - set(uniqueterms2))

3181

In [302]:
df_uterms_restrict = pd.DataFrame(uniqueterms2, columns=['term'])
df_uterms_restrict.loc[df_uterms_restrict.term.notna()]

                 term
0                 nee
1             albadie
2              Ackema
3       aômirauteyten
4      aaniraliteyten
...               ...
11832            ter.
11833        pensioen
11834        stuyvers
11835        compleet
11836         Indigo.

[11836 rows x 1 columns]

In [519]:
name_merge = fuzzy_merge(df_nms, df_uterms_restrict.loc[df_uterms_restrict.term.notna()], left_on='name', right_on='term', cutoff=0.7)

In [513]:
df_nms.merge(df_uterms_restrict.loc[df_uterms_restrict.term.notna()], left_on='name', right_on='term')

,nr,name,text,text_unescaped,years,term
0,3691,Roye,(&#134; 1690) Frans officier; na 1685 uitgewek...,(† 1690) Frans officier; na 1685 uitgeweken na...,"{'year1': '', 'hyphen': None, 'year2': '1690'}",Roye
1,4285,Meel,Johan van. (1670-1744) Rotterdams regent; vro...,Johan van. (1670-1744) Rotterdams regent; vro...,"{'year1': '1670', 'hyphen': '-', 'year2': '1744'}",Meel
2,5277,Athlone,(1668-1719) [geschreven aan Heinsius] Oudste ...,(1668-1719) [geschreven aan Heinsius] Oudste ...,"{'year1': '1668', 'hyphen': '-', 'year2': '1719'}",Athlone

In [516]:
name_merge.name

0           Hurck, N
1         Sauvage, N
2        Collen, (Mr
3      Labesse, Paul
4      Cau, Nicolaas
           ...
795        Cloots, N
796      Albermat, N
797      Albermat, N
798        Brecht, N
799     Alexander, N
Name: name, Length: 800, dtype: object

In [521]:
group_heinsius = name_merge.groupby('nr').agg({'term':';'.join, 
                                   'nr':lambda x: x.iloc[0],
                                   'name':lambda x: x.iloc[0],
                                   'text':lambda x: x.iloc[0],
                                    'text_unescaped':lambda x: x.iloc[0]})

In [316]:
index_w_heinsius = name_merge.merge(indexdf, left_on='term', right_on='main_term')

In [317]:
index_w_heinsius

,nr,name,text_x,text_unescaped,term,lemma,main_term,text_y,first_line_id,first_line_scan_id,first_line_page_id,first_line_column_id,last_line_id,last_line_scan_id,last_line_page_id,last_line_column_id,invnr,year
0,3222,"Hurck, N","N. van. Advocaat in Meeuwen, 1711 gevangen ge...","N. van. Advocaat in Meeuwen, 1711 gevangen ge...",Hurck,van Hurck,Hurck,van Hurck aangefelt tot Omfanger van de Convoy...,NL-HaNA_1.01.02_3774_0022-column-2497-401-923-...,NL-HaNA_1.01.02_3774_0022,NL-HaNA_1.01.02_3774_0022-page-43,NL-HaNA_1.01.02_3774_0022-column-2497-401-923-...,NL-HaNA_1.01.02_3774_0022-column-2497-401-923-...,NL-HaNA_1.01.02_3774_0022,NL-HaNA_1.01.02_3774_0022-page-43,NL-HaNA_1.01.02_3774_0022-column-2497-401-923-...,3774.0,1719
1,3222,"Hurck, N","N. van. Advocaat in Meeuwen, 1711 gevangen ge...","N. van. Advocaat in Meeuwen, 1711 gevangen ge...",Hurck,van Hurck te,Hurck,van Hurck te berighten op de klaghten van Sloe...,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024,NL-HaNA_1.01.02_3778_0024-page-47,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024,NL-HaNA_1.01.02_3778_0024-page-47,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,3778.0,1723
2,3222,"Hurck, N","N. van. Advocaat in Meeuwen, 1711 gevangen ge...","N. van. Advocaat in Meeuwen, 1711 gevangen ge...",Hurck,van Hurck te,Hurck,beright te examineren. qor.,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024,NL-HaNA_1.01.02_3778_0024-page-47,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024,NL-HaNA_1.01.02_3778_0024-page-47,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,3778.0,1723
3,3222,"Hurck, N","N. van. Advocaat in Meeuwen, 1711 gevangen ge...","N. van. Advocaat in Meeuwen, 1711 gevangen ge...",Hurck,van Hurck te,Hurck,"rapport dien aangaande, hy Folland overgenomen...",NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024,NL-HaNA_1.01.02_3778_0024-page-47,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,NL-HaNA_1.01.02_3778_0024,NL-HaNA_1.01.02_3778_0024-page-47,NL-HaNA_1.01.02_3778_0024-column-2516-419-905-...,3778.0,1723
4,3222,"Hurck, N","N. van. Advocaat in Meeuwen, 1711 gevangen ge...","N. van. Advocaat in Meeuwen, 1711 gevangen ge...",Hurck,van Hurck,Hurck,van Hurck wegens Holland ter Generaliteyt geco...,NL-HaNA_1.01.02_3785_0026-column-1380-465-993-...,NL-HaNA_1.01.02_3785_0026,NL-HaNA_1.01.02_3785_0026-page-50,NL-HaNA_1.01.02_3785_0026-column-1380-465-993-...,NL-HaNA_1.01.02_3785_0026-column-1380-465-993-...,NL-HaNA_1.01.02_3785_0026,NL-HaNA_1.01.02_3785_0026-page-50,NL-HaNA_1.01.02_3785_0026-column-1380-465-993-...,3785.0,1730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11475,0901,"Brecht, N",N. van. N.n.g. Nederlands officier; ritmeeste...,N. van. N.n.g. Nederlands officier; ritmeeste...,recht,recht tot het,recht,"recht tot het aenfiellen van een Capelaen,",NL-HaNA_1.01.02_3769_0016-column-1446-368-894-...,NL-HaNA_1.01.02_3769_0016,NL-HaNA_1.01.02_3769_0016-page-30,NL-HaNA_1.01.02_3769_0016-column-1446-368-894-...,NL-HaNA_1.01.02_3769_0016-column-1446-368-894-...,NL-HaNA_1.01.02_3769_0016,NL-HaNA_1.01.02_3769_0016-page-30,NL-HaNA_1.01.02_3769_0016-column-1446-368-894-...,3769.0,1714
11476,0901,"Brecht, N",N. van. N.n.g. Nederlands officier; ritmeeste...,N. van. N.n.g. Nederlands officier; ritmeeste...,recht,recht,recht,recht en generael verbandt in het Quartier van,NL-HaNA_1.01.02_3770_0013-column-2503-479-877-...,NL-HaNA_1.01.02_3770_0013,NL-HaNA_1.01.02_3770_0013-page-25,NL-HaNA_1.01.02_3770_0013-column-2503-479-877-...,NL-HaNA_1.01.02_3770_0013-column-2503-479-877-...,NL-HaNA_1.01.02_3770_0013,NL-HaNA_1.01.02_3770_0013-page-25,NL-HaNA_1.01.02_3770_0013-column-2503-479-877-...,3770.0,1715
11477,0097,"Alexander, N","N. Zweeds dragoman te Bender, 1711.","N. Zweeds dragoman te Bender, 1711.",Alexander,Alexander,Alexander,Alexander om Brieven van Pardon en her- sellin...,NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,NL-HaNA_1.01.02_3778_0007,NL-HaNA_1.01.02_3778_0007-page-12,NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,NL-HaNA_1.01.02_3778_0007,NL-HaNA_1.01.02_3778_0007-page-12,NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,3778.0,1723
11478,0097,"Alexander, N","N. Zweeds dragoman te Bender, 1711.","N. Zweeds dragoman te Bender, 1711.",Alexander,Alexander,Alexander,"advis, ende m plaats van deporte- ment voor ee...",NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,NL-HaNA_1.01.02_3778_0007,NL-HaNA_1.01.02_3778_0007-page-12,NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,NL-HaNA_1.01.02_3778_0007,NL-HaNA_1.01.02_3778_0007-page-12,NL-HaNA_1.01.02_3778_0007-column-1306-430-989-...,3778.0,1723
11479,0097,"Alexander, N","N. Zweeds dragoman te Bender, 1711.","N. Zweeds dragoman te Bender, 1711.",Alexander,Alexander,Alexander,"Alexander, Pasport ad omnes Populos. 354.",NL-HaNA_1.01.02_3789_0007-column-2625-477-955-...,NL-HaNA_1.01.02_3789_0007,NL-HaNA_1.01.02_3789_0007-page-13,NL-HaNA_1.01.02_3789_0007-column-2625-477-955-...,NL-HaNA_1.01.02_3789_0007-column-2625-477-955-...,NL-HaNA_1.01.02_3789_0007,NL-HaNA_1.01.02_3789_0007-page-13,NL-HaNA_1.01.02_3789_0007-column-2625-477-955-...,3789.0,1734

In [ ]:
linkterm

In [354]:
df_nms

,nr,name,text,text_unescaped,years
0,5848,"Sheffield, John, Markies van Normanby, Hertog ...",(1648-1721) Engels edelman; 1694 markies van N...,(1648-1721) Engels edelman; 1694 markies van N...,"{'year1': '1648', 'hyphen': '-', 'year2': '1721'}"
1,5690,"Scheltinga, Martinus van",(1666-1742) Grietman van Schoterland 1692-1742...,(1666-1742) Grietman van Schoterland 1692-1742...,"{'year1': '1666', 'hyphen': '-', 'year2': '1742'}"
2,0930,"Brieux, François Moissant de",(&#134; 1727) Officier in Nederlandse dienst; ...,(† 1727) Officier in Nederlandse dienst; 1711 ...,"{'year1': '', 'hyphen': None, 'year2': '1727'}"
3,6399,"Tursi, N",N. hertog van. Genuees edelman in dienst van ...,N. hertog van. Genuees edelman in dienst van ...,None
4,1390,"Coeuvres, Maarschalk de, zie Estrées, Victor-M...",,,None
...,...,...,...,...,...
6894,0929,"Brienne, Simon de",(&#134; 1707) Kamerdienaar en barbier van Will...,(† 1707) Kamerdienaar en barbier van Willem II...,"{'year1': '', 'hyphen': None, 'year2': '1707'}"
6895,6380,"Tscharner, Niklaus",(1650-1737) [geschreven aan Heinsius] Zwiters...,(1650-1737) [geschreven aan Heinsius] Zwiters...,"{'year1': '1650', 'hyphen': '-', 'year2': '1737'}"
6896,5689,"Schellingwouw, Alida van",(&#134; 1717) Vrouwe van Poelgeest en Koudeker...,(† 1717) Vrouwe van Poelgeest en Koudekerk; si...,"{'year1': '', 'hyphen': None, 'year2': '1717'}"
6897,5851,"Sheremetov, Michael",Zoon van de voorgaande; officier; 1711 gevolma...,Zoon van de voorgaande; officier; 1711 gevolma...,"{'year1': '', 'hyphen': None, 'year2': '1711'}"
6898,4597,"Nassau-Siegen, Prins van, zie Alexis Anton Chr...","- prinses van, zie Maria Anna Josepha. - vorst...","- prinses van, zie Maria Anna Josepha. - vorst...",None

In [525]:
correspondents_merge

,personNameID,personID,lastName,firstName,infixes,firstNameFull,prefixTitle,additionalTitle,organisationName,nederlabID,...,placeOfDeath,gender,ingestTime,updateTime,lastEditedBy,modificationTime,editorialNote,isThesaurusElement,inThesaurusAs,term
0,dd2a580e-a726-74b9-7b97-0577a572962d,009e808a-ccbe-614a-5687-459ce22d1aa0,Puy,Marc,du,Marc,,,,009e808a-ccbe-614a-5687-459ce22d1aa0,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Puy
1,81ca5418-0590-6724-a732-1b31d671628d,0114add4-9790-3ae6-80b5-1aa41ea0b0f6,Cuper,Gisbert,,Gisbert,,,,0114add4-9790-3ae6-80b5-1aa41ea0b0f6,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Cuper
2,5c1c8cc7-c894-0b56-77c6-de20d9519d0f,02ade037-4743-7778-2b59-82de8e6d3fbb,Staphorstius,Samuel,,Samuel,,,,02ade037-4743-7778-2b59-82de8e6d3fbb,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Staphorttius
3,cfbd4a31-b220-9f12-e92b-35a5c51e10f8,0344dc70-7df2-abc2-b8ce-532fa3eddfc4,Broeckhuysen,Wilt Johan,van,Wilt Johan,,heer van de Lathmer en Wilp,,0344dc70-7df2-abc2-b8ce-532fa3eddfc4,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Broeckhuysen
4,cfbd4a31-b220-9f12-e92b-35a5c51e10f8,0344dc70-7df2-abc2-b8ce-532fa3eddfc4,Broeckhuysen,Wilt Johan,van,Wilt Johan,,heer van de Lathmer en Wilp,,0344dc70-7df2-abc2-b8ce-532fa3eddfc4,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Broeekhuysen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,4d717a61-0607-4327-0281-b0687c557f12,fe721096-bbfe-fcb8-e1f8-9d52f92747a7,Salisch,Ernst Willem,van,Ernst Willem,,,,fe721096-bbfe-fcb8-e1f8-9d52f92747a7,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Salisch
792,cd8405a6-59fd-3650-e057-b19ffbe0282a,feb2c1d2-56be-1338-39c6-6621c402dfa6,Bentheim-Steinfurt,Status Philipp,van,Status Philipp,graaf,,,feb2c1d2-56be-1338-39c6-6621c402dfa6,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Benthein-Steinfurt
793,cd8405a6-59fd-3650-e057-b19ffbe0282a,feb2c1d2-56be-1338-39c6-6621c402dfa6,Bentheim-Steinfurt,Status Philipp,van,Status Philipp,graaf,,,feb2c1d2-56be-1338-39c6-6621c402dfa6,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Benthem-Steinfort
794,cd8405a6-59fd-3650-e057-b19ffbe0282a,feb2c1d2-56be-1338-39c6-6621c402dfa6,Bentheim-Steinfurt,Status Philipp,van,Status Philipp,graaf,,,feb2c1d2-56be-1338-39c6-6621c402dfa6,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Bentheim-Steinfurt
795,cd8405a6-59fd-3650-e057-b19ffbe0282a,feb2c1d2-56be-1338-39c6-6621c402dfa6,Bentheim-Steinfurt,Status Philipp,van,Status Philipp,graaf,,,feb2c1d2-56be-1338-39c6-6621c402dfa6,...,,u,2017-07-04 18:04:02,0000-00-00 00:00:00,,NaT,,0,None,Bentheim-Steinturt

In [530]:
correspondents_merge.groupby('personID').agg({'term':';'.join, 
                                   'lastName':lambda x: x.iloc[0],
                                   'firstName':lambda x: x.iloc[0],
                                   'infixes':lambda x: x.iloc[0],
                                   
                                    })

,term,lastName,firstName,infixes
personID,,,,
009e808a-ccbe-614a-5687-459ce22d1aa0,Puy,Puy,Marc,du
0114add4-9790-3ae6-80b5-1aa41ea0b0f6,Cuper,Cuper,Gisbert,
02ade037-4743-7778-2b59-82de8e6d3fbb,Staphorttius,Staphorstius,Samuel,
0344dc70-7df2-abc2-b8ce-532fa3eddfc4,Broeckhuysen;Broeekhuysen;Broekhuysen,Broeckhuysen,Wilt Johan,van
03731e75-c481-426e-db1c-c291255dc751,Dedel;Dedels,Dedel,Pieter,
...,...,...,...,...
fde751f0-59ef-6682-7b7c-fecacaa280cc,Schaep,Schaep,Cornelis,
fe40e8fd-81fb-30b0-3c6a-273c81f198b0,Hessen-Cassel;Hessen-Kassel,Hessen-Kassel,Friedrich,van
fe6481a3-ba8e-8522-e7eb-e10e4d38a6e5,Engelandt;Engeland;Engelande,Engeland,Anne,van
fe721096-bbfe-fcb8-e1f8-9d52f92747a7,Salisch,Salisch,Ernst Willem,van
feb2c1d2-56be-1338-39c6-6621c402dfa6,Benthein-Steinfurt;Benthem-Steinfort;Bentheim-...,Bentheim-Steinfurt,Status Philipp,van

In [411]:
heinbrieven = pd.read_csv('/Users/rikhoekstra/Downloads/heinsius_brieven/heinbrieven.csv', sep='\t')

In [412]:
heinbrieven

,Unnamed: 0,n,name,fromto,d,m,y,date,deel,page,page_index,rgp,deel.1
0,0,1,Ardes,from,1,1.0,1710.0,1 januari - 31 juli 1710,10,1,9,207,10
1,1,2,J. Dedel,from,1,1.0,1710.0,1 januari - 31 juli 1710,10,1,9,207,10
2,2,3,Van Rechteren-Almelo,from,1,1.0,1710.0,1 januari - 31 juli 1710,10,1,9,207,10
3,3,4,H.W. Rumpf,from,1,1.0,1710.0,1 januari - 31 juli 1710,10,2,10,207,10
4,4,5,Steenlack,from,1,1.0,1710.0,1 januari - 31 juli 1710,10,3,11,207,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11045,11045,905,Ph.J. van Borssele van der Hooghe,from,30,9.0,1718.0,1716-1718,18,533,542,244,18
11046,11046,906,Colyer,from,30,9.0,1718.0,1716-1718,18,534,543,244,18
11047,11047,907,Sauniere de l'Hermitage,from,30,9.0,1718.0,1716-1718,18,534,543,244,18
11048,11048,908,Beretti Landi,from,NaN,9.0,1718.0,1716-1718,18,534,543,244,18
11049,11049,909,N. Clignet,from,NaN,9.0,1718.0,1716-1718,18,535,544,244,18

In [413]:
correspondent_plus_brieven = heinbrieven.merge(correspondents_merge, left_on='name', right_on=correspondents_merge.lastName)

In [547]:
correspondent_plus_brieven['url'] = correspondent_plus_brieven.apply(lambda x: f'<a href="http://resources.huygens.knaw.nl/retroboeken/heinsius/?page={x.page_index}&source={x.deel}">brief</a>', axis=1)

In [553]:
grouped_c_p_b = correspondent_plus_brieven.groupby(['personID', 'y']).agg({'term':lambda x: x.iloc[0], 
                                   'lastName':lambda x: x.iloc[0],
                                   'firstName':lambda x: x.iloc[0],
                                   'infixes':lambda x: x.iloc[0],
                                   'name':lambda x: x.iloc[0],
                                   'd':lambda x: x.iloc[0],
                                   'm':lambda x: x.iloc[0], 
                                   'y':lambda x: x.iloc[0], 
                                   'page':lambda x: x.iloc[0],
                                   'page_index':lambda x: x.iloc[0], 
                                   'deel':lambda x: x.iloc[0],
                                   'fromto':lambda x: x.iloc[0],
                                   'url':lambda x: x.iloc[0]})

In [554]:
grouped_c_p_b

                                                    term     lastName  \
personID                             y
0114add4-9790-3ae6-80b5-1aa41ea0b0f6 1712.0        Cuper        Cuper
                                     1714.0        Cuper        Cuper
03f72baa-0461-5958-cec2-a2e03e9b14fb 1717.0     Repelaer     Repelaer
05e34118-f77c-bde5-feae-0dcb09248096 1712.0      Flotard      Flotard
07972f47-a849-aa0a-23a6-cbb1ba9ad80e 1717.0    Vleertman    Vleertman
...                                                  ...          ...
fb899a6e-747a-590d-300b-20d59b6fd27f 1715.0  Weinghuysen  Weinghuysen
fbaf3dfe-5183-027c-3d14-b2de10cc25d6 1710.0    Cavallier     Cavalier
                                     1712.0    Cavallier     Cavalier
                                     1714.0    Cavallier     Cavalier
fde751f0-59ef-6682-7b7c-fecacaa280cc 1715.0       Schaep       Schaep

                                            firstName infixes         name  \
personID                             y
0114add4-9790-3ae6-80b5-1aa41ea0b0f6 1712.0   Gisbert                Cuper
                                     1714.0   Gisbert                Cuper
03f72baa-0461-5958-cec2-a2e03e9b14fb 1717.0      Hugo             Repelaer
05e34118-f77c-bde5-feae-0dcb09248096 1712.0     David              Flotard
07972f47-a849-aa0a-23a6-cbb1ba9ad80e 1717.0    Willem            Vleertman
...                                               ...     ...          ...
fb899a6e-747a-590d-300b-20d59b6fd27f 1715.0   Hendrik          Weinghuysen
fbaf3dfe-5183-027c-3d14-b2de10cc25d6 1710.0                       Cavalier
                                     1712.0                       Cavalier
                                     1714.0                       Cavalier
fde751f0-59ef-6682-7b7c-fecacaa280cc 1715.0  Cornelis               Schaep

                                              d     m       y  page  \
personID                             y
0114add4-9790-3ae6-80b5-1aa41ea0b0f6 1712.0  22  10.0  1712.0   150
                                     1714.0  16   9.0  1714.0   219
03f72baa-0461-5958-cec2-a2e03e9b14fb 1717.0   3   8.0  1717.0   297
05e34118-f77c-bde5-feae-0dcb09248096 1712.0  27   7.0  1712.0   581
07972f47-a849-aa0a-23a6-cbb1ba9ad80e 1717.0  21   2.0  1717.0   171
...                                          ..   ...     ...   ...
fb899a6e-747a-590d-300b-20d59b6fd27f 1715.0   8   2.0  1715.0   478
fbaf3dfe-5183-027c-3d14-b2de10cc25d6 1710.0   9   4.0  1710.0   243
                                     1712.0  29   3.0  1712.0   189
                                     1714.0  22   3.0  1714.0   510
fde751f0-59ef-6682-7b7c-fecacaa280cc 1715.0   7   4.0  1715.0   620

                                             page_index  deel fromto  \
personID                             y
0114add4-9790-3ae6-80b5-1aa41ea0b0f6 1712.0         159    14   from
                                     1714.0         228    16   from
03f72baa-0461-5958-cec2-a2e03e9b14fb 1717.0         306    18   from
05e34118-f77c-bde5-feae-0dcb09248096 1712.0         589    13   from
07972f47-a849-aa0a-23a6-cbb1ba9ad80e 1717.0         180    18   from
...                                                 ...   ...    ...
fb899a6e-747a-590d-300b-20d59b6fd27f 1715.0         487    16   from
fbaf3dfe-5183-027c-3d14-b2de10cc25d6 1710.0         251    10   from
                                     1712.0         197    13   from
                                     1714.0         519    15   from
fde751f0-59ef-6682-7b7c-fecacaa280cc 1715.0         629    16   from

                                                                                           url
personID                             y
0114add4-9790-3ae6-80b5-1aa41ea0b0f6 1712.0  <a href="http://resources.huygens.knaw.nl/retr...
                                     1714.0  <a href="http://resources.huygens.knaw.nl/retr...
03f72baa-0461-5958-cec2-a2e03e9b14fb 1717.0  <a href="http://resources.huygens.knaw.nl/retr...
05e34118-f77c-bde5-feae-0dcb09248096 1712.0  <a href="http://resources.huygens.knaw.nl/retr...
07972f47-a849-aa0a-23a6-cbb1ba9ad80e 1717.0  <a href="http://resources.huygens.knaw.nl/retr...
...                                                                                        ...
fb899a6e-747a-590d-300b-20d59b6fd27f 1715.0  <a href="http://resources.huygens.knaw.nl/retr...
fbaf3dfe-5183-027c-3d14-b2de10cc25d6 1710.0  <a href="http://resources.huygens.knaw.nl/retr...
                                     1712.0  <a href="http://resources.huygens.knaw.nl/retr...
                                     1714.0  <a href="http://resources.huygens.knaw.nl/retr...
fde751f0-59ef-6682-7b7c-fecacaa280cc 1715.0  <a href="http://resources.huygens.knaw.nl/retr...

[533 rows x 13 columns]

In [559]:
grouped_c_p_b.to_html('/Users/rikhoekstra/Downloads/heinsius_brieven/pers_plus_brief_hein.html', escape=False)

In [556]:
c_p_b = correspondent_plus_brieven.sort_values(['personID', 'lastName','y','m','d'])[['name', 
       'lastName', 'firstName', 'infixes',
       'prefixTitle', 'additionalTitle', 'n', 'd', 'm', 'y', 'page','page_index', 'deel', 'fromto',
       'yearOfBirthMin', 'yearOfDeathMin','term','nederlabID','personNameID', 'personID',]]

In [557]:
c_p_b.set_index(['personID', 'lastName','firstName', 'infixes', 'prefixTitle','additionalTitle','name','y'], inplace=True)

In [558]:
c_p_b['url'] = c_p_b.apply(lambda x: f'<a href="http://resources.huygens.knaw.nl/retroboeken/heinsius/?page={x.page_index}&source={x.deel}">brief</a>', axis=1)

In [458]:
c_p_b.to_html('/Users/rikhoekstra/Downloads/heinsius_brieven/pers_plus_brief2.html', escape=False)

In [459]:
def make_clickable(val):
    return '<a href="{}">{}</a>'.format(val,val)

# html= c_p_b.style.\
#             format(make_clickable, subset=pd.IndexSlice[:, pd.IndexSlice[:, 'url']]).render()

In [443]:
c_p_b.iloc[0]['url']

'http://resources.huygens.knaw.nl/retroboeken/heinsius/?page=496&source=13'

c_p_b.to_html('/Users/rikhoekstra/Downloads/heinsius_brieven/pers_plus_brief.html')

In [444]:
with open('/Users/rikhoekstra/Downloads/heinsius_brieven/pers_plus_brief.html', escape=False) as f:
    f.write(html)

In [421]:
html[:300]

'<style  type="text/css" >\n</style><table id="T_94eab_" ><thead>    <tr>        <th class="blank level0" ></th>        <th class="col_heading level0 col0" >name</th>        <th class="col_heading level0 col1" >personNameID</th>        <th class="col_heading level0 col2" >personID</th>        <th clas'

In [460]:
name_merge

,nr,name,text,text_unescaped,term
0,3222,"Hurck, N","N. van. Advocaat in Meeuwen, 1711 gevangen ge...","N. van. Advocaat in Meeuwen, 1711 gevangen ge...",Hurck
1,5647,"Sauvage, N",N. [geschreven aan Heinsius] Advocaat in Lill...,N. [geschreven aan Heinsius] Advocaat in Lill...,Sauvage
2,1409,"Collen, (Mr",) Ferdinand van. (1651-1735) [geschreven aan ...,) Ferdinand van. (1651-1735) [geschreven aan ...,Collen
3,3578,"Labesse, Paul",(&#134; 1745) [geschreven aan Heinsius] Neder...,(† 1745) [geschreven aan Heinsius] Nederlands...,Labesse
4,1192,"Cau, Nicolaas",(1678-1743) Nederlands marine-officier; 1713 e...,(1678-1743) Nederlands marine-officier; 1713 e...,Nicolaas
...,...,...,...,...,...
795,1362,"Cloots, N",N. Koopman te Amsterdam.,N. Koopman te Amsterdam.,Cloots
796,0068,"Albermat, N",N. N.n.g. Frans inspecteur-generaal en monste...,N. N.n.g. Frans inspecteur-generaal en monste...,Albematle
797,0068,"Albermat, N",N. N.n.g. Frans inspecteur-generaal en monste...,N. N.n.g. Frans inspecteur-generaal en monste...,Albertoma
798,0901,"Brecht, N",N. van. N.n.g. Nederlands officier; ritmeeste...,N. van. N.n.g. Nederlands officier; ritmeeste...,recht
799,0097,"Alexander, N","N. Zweeds dragoman te Bender, 1711.","N. Zweeds dragoman te Bender, 1711.",Alexander